#!/usr/bin/env bash
# This script will accept a string as arg and display ip adress and ping the ip 5 times

if [ "$1" == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
